### ISSUE TITLE
Thanks thread -- share your thanks here!

### ISSUE THREAD

**Issue by mspanish** [agilgur5/trim-canvas#2]
I'm using from browser, not Node.js - but it was easy to adjust - and this script works beautifully!  Thank you very much.

**Comment by agilgur5** [comment]
You're welcome! For future reference, issues are not a good place to express thanks (they're mainly for, well, issues), star and share always welcome though :)

**Comment by agilgur5** [comment]
I changed my opinion on this at some point in time due to seeing "what companies use this library?" issue threads and because thanks are always appreciated 😄 . Pinned and changed the name so it can be a more generic thread if anyone wants to add!

**Comment by danjdewhurst** [comment]
Useful library I've used a few times, appreciate the work. :)
