### ISSUE TITLE
Small canvas does not display

### ISSUE THREAD

**Issue by minhnhatspk** [agilgur5/trim-canvas#5]
I use `https://github.com/szimek/signature_pad` to draw the signature.
At the end of its README, it recommends trim-canvas to remove the empty space in the signature.
when I draw enough big signature, there's no problem with your module. I receive a long base64 string.
But draw a small signature, see attached:
![image](https://user-images.githubusercontent.com/21996261/50471998-94ccf200-09e9-11e9-843f-90ba9fbcc63d.png),I only receive a short base64 string that looks like this
```
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEIAAAAvCAYAAABXPhxsAAAEwUlEQ…IXfsNnrkB0QTFSTLZ+d+XSRKK89XLFfRlE9rnoPa7RKPsfPO7TLMx/kHIAAAAASUVORK5CYII=
```
This base64 image is broken, it does not display.

How do you guys think about it?
I could notify to the user that "Your signature is too small, try with a bigger one" :))

The following solution also has the same problem as above.
https://github.com/szimek/signature_pad/issues/49#issuecomment-260976909

**Comment by agilgur5** [comment]
Hi, I actually tried this a while ago and was unable to reproduce this issue.

I just published https://agilgur5.github.io/react-signature-canvas/ for example & reproduction purposes and similarly cannot reproduce this issue there. The bottom-left is an `<img src={trimmedBase64DataUrl} />` and it always displays something during my usage. Even a single dot trims properly.

Here's a screen recording of me being unable to reproduce this: https://www.loom.com/share/367004f8947841408e394656f7ba701d . If you can reproduce this on the example site, please link to a screen recording of it.

<hr>

The comment/code you linked is not relevant. Per the code and the text of the comment by the author, the only difference there is that it duplicates the canvas. The actual trimming is virtually equivalent (almost every piece of code in the thread is virtually the same).
